// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY84rdqVJQGWV8IrlIJYCPlI9_0wnR5Uk',
    appId: '1:22786746100:web:a2d0ec43606a853206a0a1',
    messagingSenderId: '22786746100',
    projectId: 'wavlength-3e66a',
    authDomain: 'wavlength-3e66a.firebaseapp.com',
    storageBucket: 'wavlength-3e66a.appspot.com',
    measurementId: 'G-K1WZ3XTE4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCitZojXmlHkE8suZtWwGwDGFM0wC-SkzU',
    appId: '1:22786746100:android:4b5dc330316fb9c106a0a1',
    messagingSenderId: '22786746100',
    projectId: 'wavlength-3e66a',
    storageBucket: 'wavlength-3e66a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqH1wmPnRKJZwdk25_AnqDRW6C6mi_kJQ',
    appId: '1:22786746100:ios:a3c88fd0c2d6351f06a0a1',
    messagingSenderId: '22786746100',
    projectId: 'wavlength-3e66a',
    storageBucket: 'wavlength-3e66a.appspot.com',
    iosClientId: '22786746100-jtm64ha0qrt62jcabj7i4uosv64qrdiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wavlengthApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqH1wmPnRKJZwdk25_AnqDRW6C6mi_kJQ',
    appId: '1:22786746100:ios:a3c88fd0c2d6351f06a0a1',
    messagingSenderId: '22786746100',
    projectId: 'wavlength-3e66a',
    storageBucket: 'wavlength-3e66a.appspot.com',
    iosClientId: '22786746100-jtm64ha0qrt62jcabj7i4uosv64qrdiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wavlengthApplication',
  );
}
